---
# postgres
- name: Pull postgres image
  community.docker.docker_image:
    name: '{{ postgres_img_repo }}'
    repository: '{{ docker_registry_url }}/{{ postgres_img }}'
    source: pull
    push: true

# nextcloud
- name: Pull nextcloud image
  community.docker.docker_image:
    name: '{{ nextcloud_img_repo }}'
    repository: '{{ docker_registry_url }}/{{ nextcloud_img }}'
    source: pull
    push: true

# keycloak
- name: Pull Keycloak image
  community.docker.docker_image:
    name: '{{ keycloak_img_repo }}'
    repository: '{{ docker_registry_url }}/{{ keycloak_img }}'
    source: pull
    push: true

# traefik
- name: Get traefik image
  community.docker.docker_image:
    name: '{{ traefik_img_repo }}'
    repository: '{{ docker_registry_url }}/{{ traefik_img }}'
    source: pull
    push: true

# fluent-bit
- name: Get fluent-bit image
  community.docker.docker_image:
    name: '{{ fluentbit_img_repo }}'
    repository: '{{ docker_registry_url }}/{{ fluentbit_img }}'
    source: pull
    push: true

# prometheus
- name: Get prometheus image
  community.docker.docker_image:
    name: '{{ prometheus_img_repo }}'
    repository: '{{ docker_registry_url }}/{{ prometheus_img }}'
    source: pull
    push: true

# loki
# Warn: tag is only 2.7.1 (no v) -> https://github.com/grafana/loki/releases/tag/v2.7.1
- name: Get loki image
  community.docker.docker_image:
    name: '{{ loki_img_repo }}'
    repository: '{{ docker_registry_url }}/{{ loki_img }}'
    source: pull
    push: true

# grafana
- name: Get grafana image
  community.docker.docker_image:
    name: '{{ grafana_img_repo }}'
    repository: '{{ docker_registry_url }}/{{ grafana_img }}'
    source: pull
    push: true
