---
# traefik
- name: Pull traefik image
  community.docker.docker_image:
    name: traefik:v2.9.6
    repository: "{{ docker_registry_url }}/traefik:v2.9.6"
    source: pull
    push: true
  when: inventory_hostname == groups['swarm_managers'][0]

# postgres
- name: Pull postgres image
  community.docker.docker_image:
    name: postgres:15.1
    repository: "{{ docker_registry_url }}/postgres:15.1"
    source: pull
    push: true
  when: inventory_hostname == groups['swarm_managers'][0]

# nextcloud
- name: Pull nextcloud image
  community.docker.docker_image:
    name: "nextcloud:23.0-apache"
    repository: "{{ docker_registry_url }}/nextcloud:23.0-apache"
    source: pull
    push: true
  when: inventory_hostname == groups['swarm_managers'][0]

# keycloak
- name: Pull Keycloak image
  community.docker.docker_image:
    name: quay.io/keycloak/keycloak:20.0.1
    repository: "{{ docker_registry_url }}/keycloak:20.0.1"
    source: pull
    push: true
  when: inventory_hostname == groups['swarm_managers'][0]

# traefik
- name: Get traefik image
  community.docker.docker_image:
    name: traefik:v2.9.6
    repository: "{{ docker_registry_url }}/traefik:v2.9.6"
    source: pull
    push: true
  when: inventory_hostname == groups['swarm_managers'][0]

# fluent-bit
- name: Get fluent-bit image
  community.docker.docker_image:
    name: cr.fluentbit.io/fluent/fluent-bit:2.0.6
    repository: "{{ docker_registry_url }}/fluent-bit:2.0.6"
    source: pull
    push: true
  when: inventory_hostname == groups['swarm_managers'][0]

# prometheus
- name: Get prometheus image
  community.docker.docker_image:
    name: prom/prometheus:v2.40.6
    repository: "{{ docker_registry_url }}/prometheus:v2.40.6"
    source: pull
    push: true
  when: inventory_hostname == groups['swarm_managers'][0]

# grafana
# Warn: tag is only 2.7.1 (no v) -> https://github.com/grafana/loki/releases/tag/v2.7.1
- name: Get grafana image
  community.docker.docker_image:
    name: grafana/loki:2.7.1
    repository: "{{ docker_registry_url }}/grafana:2.7.1"
    source: pull
    push: true
  when: inventory_hostname == groups['swarm_managers'][0]
