---
# Create usernames and passowrds for Docker registry
- name: Install passlib
  ansible.builtin.pip:
    name: passlib
    state: present

- name: Create user and password for Docker registry
  community.general.htpasswd:
    path: "{{ registry_htpasswd_path }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    state: present
    mode: 0644

# Launch setup tasks for registry
# - setup_registry.yml for registry
# - setup_registry_cache.yml for registry cache (not working)
- name: Setup
  ansible.builtin.include_tasks: setup_registry.yml

- name: Install Docker registry
  community.docker.docker_swarm_service:
    name: registry
    image: "{{ registry_image }}"
    publish:
      - published_port: "{{ registry_port }}"
        target_port: "5000"
    placement:
      constraints:
        - node.role == manager
    replicas: 1
    mounts:
      - source: "{{ registry_volume }}"
        target: /var/lib/registry
      - source: "{{ registry_htpasswd_path }}"
        target: /auth
    labels:
      com.docker.swarm.service.env: "
        REGISTRY_HTTP_ADDR: :5000
        REGISTRY_HTTP_SECRET: {{ ALongRandomSecretForRegistry }}
        REGISTRY_AUTH: htpasswd
        REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        REGISTRY_AUTH_HTPASSWD_PATH: {{ registry_htpasswd_path }}
        REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
        REGISTRY_STORAGE_DELETE_ENABLED: true
        REGISTRY_VALIDATION_DISABLED: true
        "
    state: present
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Wait for registry to start
  ansible.builtin.wait_for:
    host: "{{ docker_registry_ip }}"
    port: "{{ registry_port }}"
    state: started
    timeout: 120
    delay: 1

- name: Login to registry
  community.docker.docker_login:
    registry_url: "{{ docker_registry_url }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"

- name: Install docker-compose
  ansible.builtin.pip:
    name: docker-compose
    state: present

- name: Launch download-images.yml
  ansible.builtin.include_tasks: download_images.yml
