---
- name: Create /data/docker-registry
  ansible.builtin.file:
    path: /data/docker-registry
    state: directory
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname == groups['nfs_servers'][0]

- name: Set facts for registry url
  ansible.builtin.set_fact:
    docker_registry_ip: "{{ hostvars[groups['swarm_managers'][0]]['ansible_host'] }}"
    docker_registry_url: "{{ hostvars[groups['swarm_managers'][0]]['ansible_host'] }}:5000"

- name: Install Docker registry
  community.docker.docker_swarm_service:
    name: registry
    image: "{{ registry_image }}"
    labels:
      com.docker.swarm.constraints: "node.hostname==node1"
      com.docker.swarm.service.publish: "{{ registry_port }}:5000"
      com.docker.swarm.service.mount: "{{ registry_volume }}:/var/lib/registry"
    state: present
  when: inventory_hostname == groups['swarm_managers'][0]
