---
- name: Setup
  ansible.builtin.include_tasks: setup_registry.yml

- name: Install Docker registry
  community.docker.docker_swarm_service:
    name: registry
    image: "{{ registry_image }}"
    publish:
      - published_port: "{{ registry_port }}"
        target_port: "5000"
    placement:
      constraints:
        - node.role == manager
    replicas: 1
    mounts:
      - source: "{{ registry_volume }}"
        target: /var/lib/registry
      - source: "{{ registry_htpasswd_path }}"
        target: /auth
    labels:
      # set user and password for registry
      com.docker.swarm.service.env: "
        HTTP_ADDR: :5000
        REGISTRY_HTTP_ADDR: :5000
        REGISTRY_AUTH: htpasswd
        REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        REGISTRY_AUTH_HTPASSWD_PATH: {{ registry_htpasswd_path }}
        REGISTRY_HTTP_SECRET: ALongRandomSecretForRegistry
        REGISTRY_STORAGE_DELETE_ENABLED: true
        DOCKER_REGISTRY_HTTP_TLS_VERIFY: false
        HTTPS: false
        "
    state: present
  when: inventory_hostname == groups['swarm_managers'][0]

# - name: Set up the registry cache
#   ansible.builtin.include_tasks: setup_registry_cache.yml

- name: Wait for registry to start
  ansible.builtin.wait_for:
    host: "{{ docker_registry_ip }}"
    port: "{{ registry_port }}"
    state: started
    timeout: 15
    delay: 1

- name: Login to registry
  community.docker.docker_login:
    registry_url: "{{ docker_registry_url }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
