---
- name: Set facts for registry url
  ansible.builtin.set_fact:
    docker_registry_ip: "{{ hostvars[groups['swarm_managers'][0]]['ansible_host'] }}"
    docker_registry_url: "{{ hostvars[groups['swarm_managers'][0]]['ansible_host'] }}:{{ registry_port }}"

- name: Create registry directory
  ansible.builtin.file:
    path: "{{ registry_cache_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname == groups['nfs_servers'][0]

# Setting deamon to accept insecure connections and use the registry as a mirror
- name: Set deamon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["{{ docker_registry_url }}"],
        "registry-mirrors": ["http://{{ docker_registry_url }}"]
      }
    force: true
    owner: root
    group: root
    mode: 0644

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
