---
- name: Set facts for registry url
  ansible.builtin.set_fact:
    docker_registry_ip: "{{ hostvars[groups['swarm_managers'][0]]['ansible_host'] }}"
    docker_registry_url: "{{ hostvars[groups['swarm_managers'][0]]['ansible_host'] }}:{{ registry_port }}"

- name: Create /data/docker-registry
  ansible.builtin.file:
    path: "{{ registry_volume }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['nfs_servers'][0]

- name: Create /etc/docker
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: "0755"

# Setting deamon to accept insecure connections and use the registry as a mirror
- name: Set deamon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["{{ docker_registry_url }}"],
        "metrics-addr" : "0.0.0.0:9323",
        "experimental" : true
      }
    force: true
    owner: root
    group: root
    mode: "0644"

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
