---
- name: Pull Keycloak image
  community.docker.docker_image:
    name: quay.io/keycloak/keycloak:20.0.1
    repository: "{{ docker_registry_url }}/keycloak:20.0.1"
    source: pull
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Start Keycloak
  community.docker.docker_swarm_service:
    name: "keycloak"
    image: "{{ docker_registry_url }}/keycloak:20.0.1"
    env:
      NEXTCLOUD_CONTAINER_NAME: "nextcloud"
      KEYCLOAK_CONTAINER_NAME: "keycloak"
      KEYCLOAK_ADMIN_USER: "{{ keycloak_username }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ keycloak_password }}"
      SAMPLE_USER_PASSWORD: "itsdifficult"
      OIDC_CLIENT_ID: "nextcloud"
      OIDC_PROVIDER_URL: "http://{{ ansible_host }}:8080/realms/vcc"
      OIDC_LOGOUT_URL: "http://{{ ansible_host }}/apps/oidc_login/oidc"
    networks:
      - name: host
    mode: global
    publish:
      - mode: host
        published_port: 8080
        target_port: 8080
    restart_config:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
  when: inventory_hostname == groups['swarm_managers'][0]
