---
- name: Create /data/keycloak
  ansible.builtin.file:
    path: "{{ keycloak_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Copy realm-export.json to /data/keycloak using template
  ansible.builtin.template:
    src: realm-export.json
    dest: /data/keycloak/realm-export.json
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname == groups['swarm_managers'][0]
