---
- name: Pull Keycloak image
  community.docker.docker_image:
    name: quay.io/keycloak/keycloak:20.0.1
    repository: "{{ docker_registry_url }}/keycloak:20.0.1"
    source: pull
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Wait for keycloak image
  community.docker.docker_image_info:
    name: "{{ docker_registry_url }}/keycloak:20.0.1"
  register: keycloak_image
  until: keycloak_image.images | length > 0
  retries: 10
  delay: 5
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Push keycloak to registry
  community.docker.docker_image:
    name: "{{ docker_registry_url }}/keycloak:20.0.1"
    repository: "{{ docker_registry_url }}/keycloak:20.0.1"
    source: pull
    push: true
    debug: true
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Create /data/keycloak
  ansible.builtin.file:
    path: "{{ keycloak_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname == groups['swarm_managers'][0]
    
- name: Start Keycloak
  community.docker.docker_swarm_service:
    name: "keycloak"
    image: "{{ docker_registry_url }}/keycloak:20.0.1"
    mounts:
      - source: /data/keycloak
        target: /opt/keycloak/data/import
    publish:
      - mode: host
        published_port: 8080
        target_port: 8443
    networks:
      - name: host
    restart_config:
      condition: on-failure
    env:
      KEYCLOAK_CONTAINER_NAME: "keycloak"
      KEYCLOAK_ADMIN: "{{ keycloak_username }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ keycloak_password }}"
      KEYCLOAK_DB_URL: "jdbc:postgresql://{{ ansible_host }}:5432/keycloak"
      KEYCLOAK_DB_PASSWORD: "{{ postgres_password }}"
    args: "start-dev"
  when: inventory_hostname == groups['swarm_managers'][0]
