---
- name: Common part of the playbook for both nodes
  hosts: all
  become: true
  roles:
  - nfs
  - docker
  - docker_swarm
  - registry
  - database
  - keycloak
  - nextcloud
  - monitoring
  - logging
  - dashboard

# running apt update and upgrade
- name: Update and upgrade
  hosts: all
  become: true
  tasks:
  - name: Update and upgrade
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
