---
- name: Common part of the playbook for both nodes
  hosts: all
  become: true
  roles:
    # - update
    # - nfs
    # - geerlingguy.docker
    - docker_swarm
    - registry
    - database
    - compose
    # - keycloak
    # - nextcloud
    # - monitoring
    # - logging
    # - dashboard
