---
- name: Common part of the playbook for both nodes
  hosts: all
  become: true
  roles:
    # - update
    - nfs
    - docker
    - docker_swarm
    - registry
    - traefik
    - database
    - keycloak
    - nextcloud
    - monitoring
    - logging
    - dashboard
    - compose
