---
- name: Common part of the playbook for both nodes
  hosts: all
  become: true
  roles:
  - update
  - nfs
  - geerlingguy.docker
  - docker_swarm
  - registry
  - database
  - keycloak
  - nextcloud
  - monitoring
  - logging
  - dashboard
