{
 "title": "Node metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Docker status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info",
     "legendFormat": "{{job}} running on {{instance}} - {{os}} {{architecture}}"
    }
   ]
  },
  {
   "title": "Node CPUs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus", "legendFormat": "{{job}} @ {{instance}}" }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"docker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU time 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"docker\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"docker\"}",
     "legendFormat": "{{job}} on {{instance}}"
    }
   ]
  }
 ]
}