---
- name: Create /data/postgresql
  ansible.builtin.file:
    path: "{{ postgres_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname == groups['nfs_servers'][0]

- name: Pull postgres image
  community.docker.docker_image:
    name: postgres:15.1
    repository: "{{ docker_registry_url }}/postgres:15.1"
    source: pull
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Start postgres on swarm
  community.docker.docker_swarm_service:
    name: "postgres"
    image: "{{ docker_registry_url }}/postgres:15.1"
    mounts:
      - source: "{{ postgres_volume }}"
        target: "/var/lib/postgresql/data"
    publish:
      - published_port: "{{ postgres_port }}"
        target_port: "5432"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  when: inventory_hostname == groups['swarm_managers'][0]
