---
- name: Create /data/postgres
  ansible.builtin.file:
    path: "{{ postgres_volume }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['nfs_servers'][0]

- name: Create directory /data/postgres-init
  ansible.builtin.file:
    path: /data/postgres-init
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Copy init.sql to /data/postgres-init using template
  ansible.builtin.template:
    src: init.sql.j2
    dest: /data/postgres-init/init.sql
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups['swarm_managers'][0]
