---
- name: Create /data/postgresql
  ansible.builtin.file:
    path: "{{ postgres_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname == groups['nfs_servers'][0]

- name: Pull postgres image
  community.docker.docker_image:
    name: postgres:15.1
    repository: "{{ docker_registry_url }}/postgres:15.1"
    source: pull
  when: inventory_hostname == groups['swarm_managers'][0]

#wait for the image to be pulled 
- name: Wait for postgres image
  community.docker.docker_image_info:
    name: "{{ docker_registry_url }}/postgres:15.1"
  register: postgres_image
  until: postgres_image.images | length > 0
  retries: 10
  delay: 10
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Push postgres to registry
  community.docker.docker_image:
    name: keycloak
    source: local
    repository: "{{ docker_registry_url }}/postgres:15.1"
    push: true
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Start postgres on swarm
  community.docker.docker_swarm_service:
    name: "postgres"
    image: "{{ docker_registry_url }}/postgres:15.1"
    mounts:
      - source: "{{ postgres_volume }}"
        target: "/var/lib/postgresql/data"
    publish:
      - published_port: "{{ postgres_port }}"
        target_port: "5432"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  when: inventory_hostname == groups['swarm_managers'][0]
