version: '3'

services:
  postgres:
    image: "{{ docker_registry_url }}/postgres:15.1"
    volumes:
      - "/data/postgres:/var/lib/postgresql"
      - "/data/postgres-init:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    networks:
      - "skynet"
    restart: always
    environment:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      PG_DATA: "var/lib/postgresql/pgdata"

  keycloak:
    image: "{{ docker_registry_url }}/keycloak:20.0.1"
    volumes:
      - "/data/keycloak/realm-export.json:/opt/keycloak/data/import/main-realm.json"
    ports:
      - "8080:8443"
    networks:
      - "host"
      - "skynet"
    restart: on-failure
    environment:
      KC_CONTAINER_NAME: "keycloak"
      KEYCLOAK_ADMIN: "{{ keycloak_username }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ keycloak_password }}"
      KC_DB_URL: "jdbc:postgresql://{{ ansible_host }}:5432/keycloak"
      KC_DB_USERNAME: "{{ keycloak_username }}"
      KC_DB_PASSWORD: "{{ keycloak_password }}"
      KC_DB: "postgres"
    command:
      - start-dev
      - --import-realm

networks:
  skynet:
    driver: overlay
  host:
    external: true
