version: '3.3'

services:
  postgres:
    image: "{{ docker_registry_url }}/postgres:15.1"
    volumes:
      - "/data/postgres:/var/lib/postgresql/data"
      - "/data/postgres-init:/docker-entrypoint-initdb.d"
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    networks:
      - "skynet"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "{{ postgres_password }}"

  keycloak:
    image: "{{ docker_registry_url }}/keycloak:20.0.1"
    volumes:
      - "/data/keycloak/realm-export.json:/opt/keycloak/data/import/main-realm.json"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - "skynet"
    restart: on-failure
    environment:
      KC_CONTAINER_NAME: "keycloak"
      KEYCLOAK_ADMIN: "{{ keycloak_username }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ keycloak_password }}"
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB_USERNAME: "{{ keycloak_username }}"
      KC_DB_PASSWORD: "{{ keycloak_password }}"
      KC_DB: "postgres"
    command:
      - start-dev
      - --import-realm

networks:
  skynet:
    driver: overlay
