---
- name: Create /data/nextcloud
  ansible.builtin.file:
    path: "{{ nextcloud_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Place autoconfig.php inside the /data/nextcloud directory
  ansible.builtin.template:
    src: autoconfig.php.j2
    dest: /data/nextcloud/autoconfig.php
    owner: www-data
    group: www-data
    mode: 0664
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Place scripts/nextcloud-integrator.sh inside the /data/nextcloud directory
  ansible.builtin.copy:
    src: ../scripts/nextcloud-integrator.sh
    dest: /data/nextcloud/nextcloud-integrator.sh
    owner: www-data
    group: www-data
    mode: 0777
  when: inventory_hostname == groups['swarm_managers'][0]
