---
- name: Fluent-Bit
  when: inventory_hostname == groups['nfs_servers'][0]
  block:
    - name: Create /data/fluentbit
      ansible.builtin.file:
        path: "/data/fluent-bit"
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Copy fluent-bit.conf to /data/fluent-bit
      ansible.builtin.copy:
        src: ../conf/fluent-bit.conf
        dest: /data/fluent-bit/fluent-bit.conf
        owner: root
        group: root
        mode: "0777"

- name: Prometheus
  when: inventory_hostname == groups['nfs_servers'][0]
  block:
    - name: Create /data/prometheus/config
      ansible.builtin.file:
        path: "/data/prometheus/config"
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Copy prometheus-conf.yml to /data/prometheus/config
      ansible.builtin.copy:
        src: ../conf/prometheus-config.yml
        dest: /data/prometheus/config/prometheus-config.yml
        owner: root
        group: root
        mode: "0775"

- name: Loki
  when: inventory_hostname == groups['nfs_servers'][0]
  block:
    - name: Create /data/loki
      ansible.builtin.file:
        path: "/data/loki"
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Copy loki config
      ansible.builtin.copy:
        src: ../conf/loki-config.yml
        dest: /data/loki-config.yaml
        owner: root
        group: root
        mode: "0775"
