---
- name: Create /data/fluentbit
  ansible.builtin.file:
    path: "/data/fluentbit"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Copy fluent-bit.conf to /data/fluent-bit
  ansible.builtin.copy:
    src: ../conf/fluent-bit.conf
    dest: /data/fluent-bit/fluent-bit.conf
    owner: root
    group: root
    mode: "0777"
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Create /data/prometheus
  ansible.builtin.file:
    path: "/data/prometheus"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Create /data/loki
  ansible.builtin.file:
    path: "/data/loki"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Create /data/grafana
  ansible.builtin.file:
    path: "/data/grafana"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['swarm_managers'][0]
