---
- block:
  - name: Create /data/fluentbit
    ansible.builtin.file:
      path: "/data/fluent-bit"
      state: directory
      owner: root
      group: root
      mode: "0755"
  - name: Copy fluent-bit.conf to /data/fluent-bit
    ansible.builtin.copy:
      src: ../conf/fluent-bit.conf
      dest: /data/fluent-bit/fluent-bit.conf
      owner: root
      group: root
      mode: "0777"
  when: inventory_hostname == groups['nfs_servers'][0]

- block:
  - name: Create /data/prometheus
    ansible.builtin.file:
      path: "/data/prometheus"
      state: directory
      owner: root
      group: root
      mode: "0755"
  - name: Create prometheus-data folder
    ansible.builtin.file:
      path: "/data/prometheus-data"
      state: directory
      owner: root
      group: root
      mode: "0755"
  - name: Copy prometheus.yml to /data/prometheus
    ansible.builtin.copy:
      src: ../conf/prometheus-conf.yml
      dest: /data/prometheus/prometheus.yml
      owner: root
      group: root
      mode: "0775"
  when: inventory_hostname == groups['nfs_servers'][0]

- name: Create /data/loki
  ansible.builtin.file:
    path: "/data/loki"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['nfs_servers'][0]
- name: Copy loki config
  ansible.builtin.copy:
    src: ../conf/loki-conf.yml
    dest: /data/loki-conf.yaml
    owner: root
    group: root
    mode: "0775"
  when: inventory_hostname == groups['nfs_servers'][0]
