---
- name: Install nfs-kernel-server on nfs_servers
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present

- name: Enable and start nfs-kernel-server
  ansible.builtin.service:
    name: nfs-kernel-server
    enabled: true
    state: started

- name: Set export for nfs_server node
  ansible.builtin.set_fact:
    etc_exports_line: "/data {{ nfs_address }}(rw,sync,no_subtree_check)"
  when: inventory_hostname == groups['nfs_servers'][0]

- name: Add nfs_clients to export
  ansible.builtin.set_fact:
    etc_exports_line: "{{ etc_exports_line }} {{ hostvars[item]['nfs_address'] }}(rw,no_root_squash,sync,no_subtree_check)"
  loop: "{{ groups['nfs_clients'] }}"

# - name: Print etc_exports_line
#   ansible.builtin.debug:
#     msg: "{{ etc_exports_line }}"

# - name: Stop execution of playbook
#   ansible.builtin.pause:
#     prompt: "Press enter to continue"

- name: Update /etc/exports
  ansible.builtin.lineinfile:
    # line => /data 10.255.255.10(rw,sync,no_subtree_check) 10.255.255.20(rw,no_root_squash,sync,no_subtree_check)
    path: /etc/exports
    line: "{{ etc_exports_line }}"
    state: present
    create: true
    owner: root
    group: root
    mode: "0644"
  notify: Restart nfs-kernel-server

- name: Ensure handlers are notified now to ensure nfs-kernel-server is restarted
  ansible.builtin.meta: flush_handlers
