---
- name: Create /data/certs
  ansible.builtin.file:
    path: "/data/certs"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Create /data/traefik
  ansible.builtin.file:
    path: "/data/traefik"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname == groups['swarm_managers'][0]
